### ISSUE TITLE
build hints

### ISSUE THREAD

**Issue by bby-bishopclark** [Commvault/terraform-provider-commvault#2]
How does one build this project?  Even if it's a 'go install', it may be good to note that in the README.

**Comment by mvangoor** [comment]
You can use it with the latest terraform by referencing it in your code.
On this page https://registry.terraform.io/providers/Commvault/commvault/latest see the `USE PROVIDER` option

**Comment by bby-bishopclark** [comment]
Said another way, "we've massively updated the Readme and other documentation from the place-holders present 3 hours ago, including straight-forward usage information", which is a huge improvement.

https://github.com/Commvault/terraform-provider-commvault/compare/a47bf1c350e98bb5fa5dfae5c47f20d651b34aa0...d3427cfc0b04c2d8d56d5f944015ec18110a7fd8

Thanks a bunch!
