### ISSUE TITLE
Where can I find the documentation for this?

### ISSUE THREAD

**Issue by moonblade** [Commvault/terraform-provider-commvault#4]
which all resources types are available to terraform, and the mandatory and optional inputs available to each of those.

**Comment by mvangoor** [comment]
How about this? https://registry.terraform.io/providers/Commvault/commvault/latest/docs

**Comment by MurthyManoj** [comment]
All the resources are Documented now in https://registry.terraform.io/providers/Commvault/commvault/latest/docs
